### ISSUE TITLE
外部IDPとしてGoogleアカウントを利用して実稼働する場合、課金が必要となるか調査が必要

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#118]
[Identity Platform の料金](https://cloud.google.com/identity-platform/pricing?hl=ja)

**Comment by i-kaneko-abel** [comment]
OIDCのためティア 2 プロバイダの利用を想定。
1ヶ月50人未満であれば料金は発生しない。

**Comment by urabe0225** [comment]
調査済みのためクローズ
