### ISSUE TITLE
緯度経度の順序がOASIS MapとFIWARE Orionの仕様で逆になっている

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#126]
現在の実装では緯度,経度の順序だが、Orion の geo:json では経度,緯度の順番。
[orion公式 GeoJSON](https://fiware-orion.letsfiware.jp/orion-api/#geojson:~:text=%E5%B1%9E%E6%80%A7%E5%80%A4%E3%81%AF%E6%9C%89%E5%8A%B9%E3%81%AA%20GeoJSON%20%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A7%E3%81%82%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82GeoJSON%20%E3%81%AE%E5%BA%A7%E6%A8%99%E3%81%A7%E7%B5%8C%E5%BA%A6%E3%81%8C%E7%B7%AF%E5%BA%A6%E3%81%AE%E5%89%8D%E3%81%AB%E6%9D%A5%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AB%E6%B3%A8%E7%9B%AE%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84)

**Comment by i-kaneko-abel** [comment]
[一般的](https://ja.wikipedia.org/wiki/ISO_6709)には緯度,経度の順序が適切と思われる。
> 数値列（[タプル](https://ja.wikipedia.org/wiki/%E3%82%BF%E3%83%97%E3%83%AB)）では緯度を経度の先に用いる

以下、一度持ち帰っていただく。
- [ ] 今回の実装としては、フロント⇄バックエンド間では緯度,経度の順序でやりとりを行い、Orionへの通信時に経度,緯度の形に変換した実装とする。
- [ ] エクスポートしたcsvの順序が緯度経度になっているか確認

**Comment by urabe0225** [comment]
エクスポートデータの修正は別Issueに追加 #165

**Comment by Sheile** [comment]
>  今回の実装としては、フロント⇄バックエンド間では緯度,経度の順序でやりとりを行い、Orionへの通信時に経度,緯度の形に変換した実装とする。

現状では、既にこの実装になっている。

#### Orionへの登録時
```typescript
location: {
  type: 'geo:json',
  value: {
    type: 'Point',
    coordinates: [body.longitude, body.latitude],
  },
  metadata: {
    place: {
      type: 'Text',
      value: address.level4 + address.level7,
    },
  },
},
```
https://github.com/c-3lab/oasismap/blob/main/backend/src/happiness/happiness-input.service.ts#L78


#### Orionからの取得時（全体）
```
happinessEntities.forEach((entity) => {
  const [longitude, latitude] = entity.location.value.coordinates;

  const tilePoint = this.toTilePoint(latitude, longitude, mapSize);
```
https://github.com/c-3lab/oasismap/blob/main/backend/src/happiness/happiness-all.service.ts#L82

#### Orionからの取得時（個人）
```
value: {
  type: entity.location.value.type,
  // orionは経度緯度の順なので緯度経度に整形
  coordinates: [
    entity.location.value.coordinates[1],
    entity.location.value.coordinates[0],
  ],
},
```
https://github.com/c-3lab/oasismap/blob/main/backend/src/happiness/happiness-me.service.ts#L60

**Comment by urabe0225** [comment]
対応せずクローズとする
