### ISSUE TITLE
一部の端末でチェックボックスのラベルが折り返される

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#130]
Chrome開発者ツールの iPhone SE の外観で確認。

**Comment by k-oizumi-abel** [comment]
現在はどこかのタイミングで文字サイズが見直されたと思われ、再現しませんでした。
以下 iPhone SE のイメージ。
![image](https://github.com/c-3lab/oasismap/assets/88692777/e67ebafd-30dd-4ab5-9a3e-6b522f303166)

**Comment by Sheile** [comment]
現状は問題ないようですが、`white-space: nowrap` で折り返しを抑制した上で`overflow-x: hidden`, `text-overflow: ellipsis`であふれた部分を「…」で省略するという手も考えられますね。

**Comment by urabe0225** [comment]
再現されなかったためクローズ
