### ISSUE TITLE
API簡易動作確認手順がない

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#135]
認証を行っている影響でAPIにリクエスト時にダミーのAuthorizationだと弾かれてしまう。
APIの簡易動作確認をする場合、実際のトークンを取得してヘッダーのAuthorizationに設定する必要がある。

暫定手順は[こちら](https://github.com/c-3lab/oasismap/pull/61#issue-2163153233)

**Comment by urabe0225** [comment]
#240 対応済みのためクローズ
