### ISSUE TITLE
luxon側の命名規則に合わせた実装に変更する

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#137]
OASIS Mapではグラフの表示単位（月、日、時間）の識別を `period` という独自定数を使って判別している。
現在の実装では日付操作に `luxon` ライブラリを利用しているが、`period` 定数の命名規則と異なるため、
[luxon側](https://moment.github.io/luxon/api-docs/index.html#duration)に命名規則を合わせることで、メンテナンス性の向上を検討する。
変更対象のコードは主に以下が対象となる。
・[フロントエンド](https://github.com/c-3lab/oasismap/blob/main/frontend/src/types/period.ts)
・[バックエンド](https://github.com/c-3lab/oasismap/blob/63cdba657b0cd2d0cbec70ff5fd75f392a52e005/backend/src/happiness/dto/get-happiness-all.dto.ts#L4)

**Comment by urabe0225** [comment]
修正にかかるコストから本件は未対応とする
