### ISSUE TITLE
jsonwebtokenではなくjoseを使用する

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#139]
OASIS Mapではアクセストークンの検証等に `jsonwebtoken` を利用しているが、
NextAuthの内部では `jose` を利用している。
同様の処理を複数のライブラリで行っているため、
今後 `jose` に統一することで、問題の発生リスクなどを低減することができると思われる。

**Comment by urabe0225** [comment]
修正にかかるコストから本件は未対応とする
