### ISSUE TITLE
コンテナ起動時にCygnusスキーマが生成されない場合がある

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#140]
コンテナ起動時に存在チェック及び実行を追加する必要がある。
暫定の対応としては、生成されない場合、[init.sql](https://github.com/c-3lab/oasismap/blob/main/setup/init.sql)を手動実行する

**Comment by urabe0225** [comment]
手順書またはFAQに記載して対応する

**Comment by urabe0225** [comment]
#240 対応済みのためクローズ
