### ISSUE TITLE
ログインに失敗する場合がある

### ISSUE THREAD

**Issue by fwd-oki** [c-3lab/oasismap#144]
動作デモ環境でのログイン時にフロント側で以下のエラーが発生。

```
{ error: 'invalid_grant', error_description: 'Token is not active' }
```

- [x] トークン更新に失敗した場合、現在の認証情報を破棄し、/loginにリダイレクトする。

**Comment by hasebetakumi** [comment]
2024/06/19 12:50 長谷部環境で再現

#### 再現時の手順と挙動
1. 一般ユーザーでログイン
2. oasismapのタブを開いたまま1時間ほど放置（この間PCはwin + L でロックしていた）
3. nextjsのログを確認すると`{ error: 'invalid_grant', error_description: 'Token is not active' }`が記録されていた。（タブを開いて何分後に出たのかは把握していない）
4. 他のタブに移動した後、oasismapのタブに戻るたびに`{ error: 'invalid_grant', error_description: 'Token is not active' }`が記録される
5. この状態で幸福度の検索を試してみた
→検索ボタン押下後、右下に「再ログインしてください。」というsnackbarが表示され、`/login`にリダイレクトされた
6. そのまま一般ユーザーとしてログイン
7. タブの切り替えをしても`{ error: 'invalid_grant', error_description: 'Token is not active' }`は記録されなくなった
8. 幸福度の検索ボタン押下後、問題なく幸福度の収集が実行され画面表示された。`{ error: 'invalid_grant', error_description: 'Token is not active' }`も記録されなかった。

**Comment by hasebetakumi** [comment]
### 原因
リフレッシュトークンとアクセストークンの有効期限が切れた状態でトークンの更新を行う。

#### 詳細
- （確認したファイルは`frontend/src/app/api/auth/[...nextauth]/route.ts`）
- 現在、リフレッシュトークンの有効期限は30分、アクセストークンの有効期限は5分
- アクセストークンの有効期限が切れていた場合は、リフレッシュトークンを利用しトークンを更新している（アクセストークン、リフレッシュトークンともに）
- そして、リフレッシュトークンとアクセストークンの有効期限が切れていた場合は、トークンの更新処理が走るものの、リフレッシュトークンの有効期限が切れているため更新失敗。keycloakからエラーメッセージが返る（`{ error: 'invalid_grant', error_description: 'Token is not active' }`）
- ちなみにkeycloak側にもログが出ている。
  ```
  keycloak            | 2024-06-19 17:26:13,599 WARN  [org.keycloak.events] (executor-thread-40) type=REFRESH_TOKEN_ERROR, realmId=7da882b7-75ec-40b2-b99b-73f92dcaf284, clientId=general-user-client, userId=null, ipAddress=172.18.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
  ```

#### コメント
- 再現させたいときは、keycloakコンソール画面から`Realm settings -> Sessions -> SSO Session Idle（リフレッシュトークンの有効期限）` と`Realm settings -> Tokens -> Access Token Lifespan（アクセストークンの有効期限）`を短くすると良い。

#### 対応案
- トークン更新に失敗した場合、現在の認証情報を破棄し、`/login`にリダイレクトする。

**Comment by Sheile** [comment]
一般的にRefresh Tokenは90日間などの長期間を設定することが多いため、修正とは別にKeycloakの設定を変更してもよさそうですね。

一例: https://developer.freee.co.jp/news/6540

**Comment by urabe0225** [comment]
close #182
