### ISSUE TITLE
位置情報がオフ時の警告表示

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#146]
ブラウザのホップアップにて現在地情報取得を拒否した場合や、
端末自体で現在地情報取得を拒否している場合に地図自体が表示されなくなってしまう。

位置情報の取得に失敗した場合の警告表示や、
再度位置情報取得の許諾を得るためのUI設計が必要。

**Comment by urabe0225** [comment]
FAQに本件を記載し対応する

**Comment by urabe0225** [comment]
#230 と重複するためクローズ
