### ISSUE TITLE
大量のデータをインポートした直後にエクスポートするとレコードが少ない場合がある

### ISSUE THREAD

**Issue by i-kaneko-abel** [c-3lab/oasismap#184]
2000件以上の大量のデータをインポートした直後に、エクスポートするとpostgresの登録が間に合っていない様で、レコードが少ない場合がある。

**Comment by i-kaneko-abel** [comment]
postgresの登録は[FIWARE-ORION サブスクリプション](https://fiware-orion.letsfiware.jp/user/oneshot_subscription/)による登録なので、若干のタイムラグが発生するのは必然の為、対応が難しいと思われる。

**Comment by urabe0225** [comment]
Cygnusの仕様による問題のため未対応
