### ISSUE TITLE
JMeterが動く環境の構築

### ISSUE THREAD

**Issue by hasebetakumi** [c-3lab/oasismap#212]
- [x] javaが動く環境を用意（docker使わず生のjava利用）
- [x] JMeterインストール
- [x] GUIを表示
- [x] 上記手順をコメントとして残す

**Comment by hasebetakumi** [comment]
Windows11にて実施
-  Oracle Java Development Kit 22.0.2インストール
   - [公式サイト](https://www.oracle.com/java/technologies/downloads/#jdk22-windows) からx64 Installerをダウンロード
   - インストーラーを起動し、設定何も変更せずインストール。
- Apache JMeter 5.6.3インストール
  - [公式サイト](https://jmeter.apache.org/download_jmeter.cgi)からBinariesのzipファイルをダウンロード
  - 任意のディレクトリで解凍
- Apache JMeterのGUI表示
  - 2.で解凍したファイル内の`apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin\jmeter.bat`を起動

**Comment by urabe0225** [comment]
https://github.com/c-3lab/oasismap-design-data/pull/16
PRマージ済み
